#!/usr/bin/env bash

################################################################################
# Deploy Asset Bundle from UC Volume to Target Workspace
################################################################################
#
# This script downloads the generated asset bundle from a UC Volume and
# deploys it to the target workspace using the Databricks CLI.
#
# Prerequisites:
#   - Databricks CLI v0.218.0+ installed
#   - CLI profiles configured for source and target workspaces
#   - Bundle generated by Bundle_04 notebook (asset_bundle method)
#
# Usage:
#   ./deploy_asset_bundle.sh [options]
#
################################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default configuration
SOURCE_PROFILE="${SOURCE_PROFILE:-source-workspace}"
TARGET_PROFILE="${TARGET_PROFILE:-target-workspace}"
VOLUME_BASE="${VOLUME_BASE:-/Volumes/YOUR_CATALOG/YOUR_SCHEMA/dashboard_migration}"
BUNDLE_NAME="${BUNDLE_NAME:-dashboard_migration}"
LOCAL_DIR=""
CLEANUP="${CLEANUP:-false}"
DRY_RUN="${DRY_RUN:-false}"

log_info() { echo -e "${BLUE}ℹ ${NC} $1"; }
log_success() { echo -e "${GREEN}✅${NC} $1"; }
log_warning() { echo -e "${YELLOW}⚠️ ${NC} $1"; }
log_error() { echo -e "${RED}❌${NC} $1"; }

show_help() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Downloads asset bundle from UC Volume and deploys to target workspace."
    echo ""
    echo "Options:"
    echo "  --source-profile PROFILE   Source workspace CLI profile (default: source-workspace)"
    echo "  --target-profile PROFILE   Target workspace CLI profile (default: target-workspace)"
    echo "  --volume-base PATH         UC Volume base path (required)"
    echo "  --bundle-name NAME         Bundle name (default: dashboard_migration)"
    echo "  --local-dir PATH           Local directory for bundle (default: ./bundle_TIMESTAMP)"
    echo "  --cleanup                  Remove local bundle after deployment"
    echo "  --dry-run                  Download bundle but don't deploy"
    echo "  -h, --help                 Show this help"
    echo ""
    echo "Example:"
    echo "  $0 --source-profile source-workspace \\"
    echo "     --target-profile target-workspace \\"
    echo "     --volume-base /Volumes/my_catalog/my_schema/dashboard_migration"
    echo ""
}

################################################################################
# Parse Arguments
################################################################################

while [[ $# -gt 0 ]]; do
    case $1 in
        --source-profile)
            SOURCE_PROFILE="$2"
            shift 2
            ;;
        --target-profile)
            TARGET_PROFILE="$2"
            shift 2
            ;;
        --volume-base)
            VOLUME_BASE="$2"
            shift 2
            ;;
        --bundle-name)
            BUNDLE_NAME="$2"
            shift 2
            ;;
        --local-dir)
            LOCAL_DIR="$2"
            shift 2
            ;;
        --cleanup)
            CLEANUP=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

################################################################################
# Validate Configuration
################################################################################

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Deploy Asset Bundle from UC Volume                        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check for placeholder values
if [[ "$VOLUME_BASE" == *"YOUR_CATALOG"* ]] || [[ "$VOLUME_BASE" == *"YOUR_SCHEMA"* ]]; then
    log_error "Please provide --volume-base with your actual volume path"
    echo ""
    echo "Example:"
    echo "  $0 --volume-base /Volumes/my_catalog/my_schema/dashboard_migration"
    echo ""
    exit 1
fi

# Set default local directory if not provided
if [ -z "$LOCAL_DIR" ]; then
    LOCAL_DIR="./bundle_deploy_$(date +%Y%m%d_%H%M%S)"
fi

log_info "Configuration:"
echo "   • Source Profile: ${SOURCE_PROFILE}"
echo "   • Target Profile: ${TARGET_PROFILE}"
echo "   • Volume Base: ${VOLUME_BASE}"
echo "   • Bundle Name: ${BUNDLE_NAME}"
echo "   • Local Directory: ${LOCAL_DIR}"
echo "   • Cleanup After: ${CLEANUP}"
echo "   • Dry Run: ${DRY_RUN}"
echo ""

################################################################################
# Step 1: Verify CLI and Profiles
################################################################################

log_info "Step 1: Verifying CLI and profiles..."
echo ""

# Check CLI version
CLI_VERSION=$(databricks --version 2>/dev/null || echo "not found")
if [[ "$CLI_VERSION" == "not found" ]]; then
    log_error "Databricks CLI not found. Install with: pip install databricks-cli"
    exit 1
fi
log_success "CLI version: $CLI_VERSION"

# Test source profile
if ! databricks fs ls "dbfs:${VOLUME_BASE}" --profile "$SOURCE_PROFILE" >/dev/null 2>&1; then
    log_error "Cannot access volume with source profile: ${SOURCE_PROFILE}"
    echo "   Check: databricks fs ls dbfs:${VOLUME_BASE} --profile ${SOURCE_PROFILE}"
    exit 1
fi
log_success "Source profile verified: ${SOURCE_PROFILE}"

# Test target profile
if ! databricks workspace list / --profile "$TARGET_PROFILE" >/dev/null 2>&1; then
    log_error "Cannot access target workspace with profile: ${TARGET_PROFILE}"
    echo "   Check: databricks workspace list / --profile ${TARGET_PROFILE}"
    exit 1
fi
log_success "Target profile verified: ${TARGET_PROFILE}"
echo ""

################################################################################
# Step 2: Download Bundle from Volume
################################################################################

log_info "Step 2: Downloading bundle from UC Volume..."
echo ""

VOLUME_BUNDLE_PATH="dbfs:${VOLUME_BASE}/bundles/${BUNDLE_NAME}"

log_info "Source: ${VOLUME_BUNDLE_PATH}"
log_info "Destination: ${LOCAL_DIR}"
echo ""

# Create local directory
mkdir -p "${LOCAL_DIR}"

# Download bundle
if ! databricks fs cp -r "${VOLUME_BUNDLE_PATH}" "${LOCAL_DIR}" --profile "$SOURCE_PROFILE" --overwrite 2>&1; then
    log_error "Failed to download bundle from volume"
    echo ""
    echo "Check that the bundle exists:"
    echo "   databricks fs ls ${VOLUME_BUNDLE_PATH} --profile ${SOURCE_PROFILE}"
    exit 1
fi

log_success "Bundle downloaded to: ${LOCAL_DIR}"
echo ""

# Show bundle contents
log_info "Bundle contents:"
ls -la "${LOCAL_DIR}" 2>/dev/null | head -10 | sed 's/^/   /'
echo ""

################################################################################
# Step 3: Deploy Bundle to Target Workspace
################################################################################

if [ "$DRY_RUN" = "true" ]; then
    log_warning "DRY RUN: Skipping deployment"
    echo ""
    log_info "To deploy manually, run:"
    echo "   cd ${LOCAL_DIR}"
    echo "   databricks bundle deploy -t dev --profile ${TARGET_PROFILE}"
    echo ""
else
    log_info "Step 3: Deploying bundle to target workspace..."
    echo ""
    
    cd "${LOCAL_DIR}"
    
    # Validate bundle first
    log_info "Validating bundle..."
    # Try without target first (generated bundles use default), then with -t dev
    if databricks bundle validate --profile "$TARGET_PROFILE" 2>&1; then
        log_success "Bundle validation passed"
    elif databricks bundle validate -t dev --profile "$TARGET_PROFILE" 2>&1; then
        log_success "Bundle validation passed (with -t dev)"
    else
        log_warning "Bundle validation had warnings (continuing...)"
    fi
    echo ""
    
    # Deploy bundle
    log_info "Deploying bundle..."
    # Try without target first, then with -t dev
    if databricks bundle deploy --profile "$TARGET_PROFILE" 2>&1; then
        log_success "Bundle deployed successfully!"
    elif databricks bundle deploy -t dev --profile "$TARGET_PROFILE" 2>&1; then
        log_success "Bundle deployed successfully (with -t dev)!"
    else
        log_error "Bundle deployment failed"
        exit 1
    fi
    echo ""
    
    cd - >/dev/null
fi

################################################################################
# Step 4: Cleanup (Optional)
################################################################################

if [ "$CLEANUP" = "true" ] && [ "$DRY_RUN" != "true" ]; then
    log_info "Step 4: Cleaning up local bundle..."
    rm -rf "${LOCAL_DIR}"
    log_success "Local bundle removed"
    echo ""
fi

################################################################################
# Summary
################################################################################

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    DEPLOYMENT COMPLETE                        ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

if [ "$DRY_RUN" = "true" ]; then
    log_info "Dry run completed. Bundle downloaded to: ${LOCAL_DIR}"
    echo ""
    echo "Next steps:"
    echo "   1. Review bundle: cd ${LOCAL_DIR} && ls -la"
    echo "   2. Deploy: databricks bundle deploy -t dev --profile ${TARGET_PROFILE}"
else
    log_success "Dashboards deployed to target workspace!"
    echo ""
    echo "Next steps:"
    echo "   1. Verify dashboards in target workspace"
    echo "   2. Run IP cleanup if needed:"
    echo "      ./scripts/cleanup_ip_acl.sh --target-profile ${TARGET_PROFILE}"
fi
echo ""
